
import './globals.css'







export const metadata = {
  title: 'Reactors',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	

  return (
    <html lang="en">
		
		<body className=' w- w-full flex flex-col justify-center'>
			<div className=' m-auto'>
				<h1 className=' text-red-500'>	Header</h1>
				<h1>	navbar</h1>
			</div>
			
			{children}
		</body>
    </html>
  )
}
