import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Link from 'next/link'
import BlackLine from './components/BlackLine'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
		    <NavBar/>
        <BlackLine/>
        <Link href={"/"}/>
        {children}
      </body>
    </html>
  )
}
